// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJDg7BzUH1MLyT3fpmv5gq8f9FEWbt9U',
    appId: '1:780884339305:web:cd51b2480d0bcca2cc10f8',
    messagingSenderId: '780884339305',
    projectId: 'app-store-94062',
    authDomain: 'app-store-94062.firebaseapp.com',
    storageBucket: 'app-store-94062.firebasestorage.app',
    measurementId: 'G-TBVFD8MGXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8OdqWHSGIPALz4sO01eP9zec-O3KXwQs',
    appId: '1:780884339305:android:5d3fa8a56361dae2cc10f8',
    messagingSenderId: '780884339305',
    projectId: 'app-store-94062',
    storageBucket: 'app-store-94062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCveKHHsdP0H_lxW6Cwh4iafFAAeB6uTp4',
    appId: '1:780884339305:ios:72c991222af5d82ecc10f8',
    messagingSenderId: '780884339305',
    projectId: 'app-store-94062',
    storageBucket: 'app-store-94062.firebasestorage.app',
    iosBundleId: 'com.example.commerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCveKHHsdP0H_lxW6Cwh4iafFAAeB6uTp4',
    appId: '1:780884339305:ios:72c991222af5d82ecc10f8',
    messagingSenderId: '780884339305',
    projectId: 'app-store-94062',
    storageBucket: 'app-store-94062.firebasestorage.app',
    iosBundleId: 'com.example.commerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPJDg7BzUH1MLyT3fpmv5gq8f9FEWbt9U',
    appId: '1:780884339305:web:46e1563e2d69fa89cc10f8',
    messagingSenderId: '780884339305',
    projectId: 'app-store-94062',
    authDomain: 'app-store-94062.firebaseapp.com',
    storageBucket: 'app-store-94062.firebasestorage.app',
    measurementId: 'G-5D7F50BGXD',
  );
}
